#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wclean
wclean $FOAM_SRC/functionObjects/dgForces
wclean $FOAM_APP/utilities/DG/dgToVTK/dgToVTK
wclean $FOAM_APP/utilities/DG/dgToVTK
wclean $FOAM_APP/utilities/DG/dgDecomposePar
wclean $FOAM_APP/utilities/DG/dgReconstructPar
wclean $FOAM_APP/utilities/DG/applyCurveBoundary

#------------------------------------------------------------------------------
