#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType
wmake $targetType $FOAM_SRC/functionObjects/dgForces
wmake $targetType $FOAM_APP/utilities/DG/dgToVTK/dgToVTK
wmake $FOAM_APP/utilities/DG/dgToVTK
wmake $FOAM_APP/utilities/DG/dgDecomposePar
wmake $FOAM_APP/utilities/DG/dgReconstructPar
wmake $FOAM_APP/utilities/DG/applyCurveBoundary

#------------------------------------------------------------------------------
