#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2012 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeGperftools
#
# Description
#     Build script for gperftools
#
# Note
#
#------------------------------------------------------------------------------

gperftoolsPACKAGE=gperftools-svn

#------------------------------------------------------------------------------
# run from third-party directory only
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [gperftools-VERSION]

* build gperftools
      $gperftoolsPACKAGE

USAGE
    exit 1
}


# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    gperftools-[0-9]* | gperftools-svn*)
        gperftoolsPACKAGE="${1%%/}"
        shift
        ;;
    *)
        usage "unknown option/argument: '$*'"
        ;;
    esac
done

#------------------------------------------------------------------------------
# build/install without compiler name
prefixDIR=$installBASE/$gperftoolsPACKAGE

#
# Build gperftools
#
echo "---------------"
if [ -d "$prefixDIR" ]
then
    echo "Already built: $gperftoolsPACKAGE"
else
    echo "Starting build: $gperftoolsPACKAGE"
(
    sourceDIR=$WM_THIRD_PARTY_DIR/$gperftoolsPACKAGE
    buildDIR=$buildBASE/$gperftoolsPACKAGE

    cd $sourceDIR || exit 1
    make distclean 2>/dev/null

    rm -rf $buildDIR
    mkdir -p $buildDIR
    cd $buildDIR

    # remove old junk
    rm -rf $prefixDIR

    $sourceDIR/configure \
        --prefix=$prefixDIR \
    && make -j $WM_NCOMPPROCS \
    && make install \
    && echo "Built: $gperftoolsPACKAGE" \
) || {
    echo "Error building: $gperftoolsPACKAGE"
    exit 1
}
fi

#------------------------------------------------------------------------------
