#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011-2016 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeLLVM
#
# Description
#     Build script for llvm/clang etc.
#
#    - Checkout LLVM:
#        svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm-svn
#
#    - Checkout Clang:
#        cd llvm-svn/tools
#        svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
#        cd -
#
#------------------------------------------------------------------------------

# get default llvm version
. $WM_PROJECT_DIR/etc/config.sh/functions
_foamSource $($WM_PROJECT_DIR/bin/foamEtcFile config.sh/compiler)

llvmPACKAGE=${clang_version:-llvm-3.6.0}

#------------------------------------------------------------------------------
# run from third-party directory only
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [llvm-VERSION]

* build llvm/clang
      $llvmPACKAGE

USAGE
    exit 1
}


# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    llvm-[0-9]* | llvm-svn*)
        llvmPACKAGE="${1%%/}"
        shift
        ;;
    *)
        usage "unknown option/argument: '$*'"
        ;;
    esac
done

#------------------------------------------------------------------------------
# build/install without compiler name
buildBASE=$WM_THIRD_PARTY_DIR/build/$WM_ARCH$WM_COMPILER_ARCH
installBASE=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH

LLVM_ARCH_PATH=$installBASE/$llvmPACKAGE

# name of source directory
# - may have a llvm/ subdirectory, depending on how the sources were fetched
#
sourceDIR=$WM_THIRD_PARTY_DIR/$llvmPACKAGE
if [ -f $sourceDIR/llvm/configure ]
then
    sourceDIR=$sourceDIR/llvm
fi

#
# Build LLVM
#
echo "---------------"
if [ -d $LLVM_ARCH_PATH ]
then
    echo "Already built: $llvmPACKAGE"
else
    echo "Starting build: $llvmPACKAGE"
    echo
(
    cd $sourceDIR || exit 1
    make distclean 2>/dev/null

    buildDIR=$buildBASE/$llvmPACKAGE
    rm -rf $buildDIR
    mkdir -p $buildDIR
    cd $buildDIR

    set -x
    $sourceDIR/configure \
        --prefix=$LLVM_ARCH_PATH \
        --with-gcc-toolchain=`which gcc | sed s%/bin/gcc%%` \
        --enable-optimized \
    && make -j $WM_NCOMPPROCS \
    && make install \
    && echo "Built: $llvmPACKAGE"
) || {
    echo "Error building: $llvmPACKAGE"
    exit 1
}
fi

#------------------------------------------------------------------------------
